version: '3.8'

services:
  # Frontend-Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Entferne die statische API URL, damit unsere dynamische Logik im JS-Code greift
      # - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped

  # Backend-Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # Entferne die externe Port-Freigabe, nur intern erreichbar
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"  # Nur intern im Docker-Netzwerk verfügbar
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/kitchen-assistant
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRE=30d
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb
    restart: unless-stopped

  # MongoDB-Datenbankservice
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=kitchen-assistant
    restart: unless-stopped

volumes:
  mongodb_data: 