services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      # Mount the entire app for development
      - ./frontend:/app/frontend
      # Named volume for persistent data storage
      - recipe_data:/app/data
      # ALSA configuration
      - /etc/asound.conf:/etc/asound.conf:ro
      - /usr/share/alsa:/usr/share/alsa:ro
    env_file:
      - ./backend/.env
    environment:
      - FLASK_DEBUG=true
    restart: unless-stopped
    # Command that overrides the default entrypoint for development
    command: python backend/app.py
    # Add audio device access
    devices:
      - "/dev/snd:/dev/snd"

volumes:
  recipe_data:
    # This named volume will persist the recipe data between container restarts

